import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: [
    { path: "../../public/fonts/Satoshi-Regular.otf", weight: "400" },
    { path: "../../public/fonts/Satoshi-Medium.otf", weight: "500" },
    { path: "../../public/fonts/Satoshi-Bold.otf", weight: "900" },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "jointherealworldnetwork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${satoshi.variable} ${leagueSpartan.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
